name = "c-ziperr"
main = "worker/src/index.js"
compatibility_date = "2026-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
GH_REPO = "v1-byte/C_Ziperr"
GH_REF = "main"
# Secret (jangan ditulis di sini): GH_TOKEN
