import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../public/index.html', import.meta.url), 'utf8');
assert.match(html, /id="collect-ai-readiness"/);
assert.match(html, /id="collect-ai-status"/);
assert.match(html, /id="offline-ready-ai"/);
assert.match(html, /id="offline-ready-play"/);
assert.match(html, /function playOfflineReview\(/);
assert.match(html, /function gcRunOfflineReadinessAssistant\(/);
assert.match(html, /function gcAiRepairOfflineFiles\(/);
assert.match(html, /BACKUP\/AI-OFFLINE/);
assert.match(html, /introducesMissingLocalRefs/);
assert.match(html, /AI Auto Offline/);
assert.match(html, /callCustomAIWithFailover\(\[/);
assert.match(html, /Cloudflare Capture/);
assert.match(html, /GitHub Actions Collect/);
assert.match(html, /browser network-off/i);
assert.doesNotMatch(html, /id="gc-authorized-research"|id="gc-license-ref"|id="gc-challenge-manual"/);
assert.doesNotMatch(html, /function gcValidateResearchOptions\(/);
assert.match(html, /id="gc-github-token-modal"/);
assert.match(html, /X-GC-GitHub-Token/);
assert.doesNotMatch(html, /localStorage\.setItem\([^\n]*[Gg]ithub[^\n]*token/i);
assert.doesNotMatch(html, /sessionStorage\.setItem\([^\n]*[Gg]ithub[^\n]*token/i);
assert.match(html, /mock-offline/);
console.log('collect AI readiness assistant test passed');
