import { readFile, readdir, stat } from 'node:fs/promises';
import { join, relative, extname } from 'node:path';

export async function validateOffline(root, { entry = 'index.rendered.html' } = {}) {
  const files = new Set((await walk(root)).map(x => relative(root, x).replaceAll('\\', '/'))), entryPath = files.has(entry) ? entry : [...files].find(x => /(^|\/)index\.html?$/i.test(x));
  const missing = [], external = [], apiRefs = [], warnings = []; if (!entryPath) missing.push({ from: '(root)', target: entry, reason: 'entry-missing' });
  const textFiles = [...files].filter(x => ['.html', '.htm', '.js', '.mjs', '.css'].includes(extname(x).toLowerCase()));
  for (const rel of textFiles) { const text = await readFile(join(root, rel), 'utf8'); for (const m of text.matchAll(/(?:src|href|url|import\s*\(|fetch\s*\()\s*[=(]?\s*["'`]([^"'`#]+)["'`]/g)) { const target = m[1]; if (/^(data:|blob:|javascript:|#)/i.test(target)) continue; if (/^https?:\/\//i.test(target)) { external.push({ from: rel, target }); continue; } if (target.startsWith('/api/') || target.includes('/api/')) { apiRefs.push({ from: rel, target }); continue; } const clean = target.split('?')[0].replace(/^\.\//, ''); const base = rel.includes('/') ? rel.slice(0, rel.lastIndexOf('/') + 1) : ''; const normalized = normalize(base + clean); if (!files.has(normalized) && !files.has(normalized.replace(/^\//, ''))) missing.push({ from: rel, target, normalized, reason: 'local-resource-missing' }); } }
  const apiRules = files.has('mock-api.json') ? JSON.parse(await readFile(join(root, 'mock-api.json'), 'utf8')).length : files.has('server') ? [...files].filter(x => x.startsWith('server/') && x.endsWith('.json')).length : 0;
  if (external.length) warnings.push('Masih ada URL external; gunakan mock/rewrite untuk mode network-off.'); if (apiRefs.length && !apiRules) warnings.push('Ada referensi API tetapi belum ada server/*.json atau mock-api.json.');
  const required = [entryPath, 'kelengkapan.json'].filter(Boolean), passed = required.filter(x => files.has(x)).length; const score = Math.max(0, Math.round(100 * ((passed / Math.max(required.length, 1)) * 0.35 + (missing.length === 0 ? 0.35 : Math.max(0, 0.35 - missing.length * 0.01)) + (apiRefs.length === 0 || apiRules ? 0.2 : 0) + (external.length === 0 ? 0.1 : 0)))); const status = score >= 90 && missing.length === 0 && (!apiRefs.length || apiRules) ? 'FULL_OFFLINE_READY' : score >= 60 ? 'PARTIAL' : 'NOT_READY';
  return { generatedAt: new Date().toISOString(), root, entry: entryPath, status, score, files: files.size, missing, external, apiRefs, apiRules, warnings };
}
async function walk(root) { const out = []; for (const name of await readdir(root)) { const p = join(root, name), s = await stat(p); if (s.isDirectory() && !name.startsWith('.')) out.push(...await walk(p)); else if (s.isFile()) out.push(p); } return out; }
function normalize(p) { const parts = []; for (const x of p.split('/')) { if (!x || x === '.') continue; if (x === '..') parts.pop(); else parts.push(x); } return parts.join('/'); }
