// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/workspace-preview/WorkspacePreview.tsx": () => import("../components/mockups/workspace-preview/WorkspacePreview.tsx")
};
